import StickyContact from '@/components/StickyContact';

export default function PrivacyPolicy() {
  return (
    <>
      <main className="min-h-screen bg-white">
        {/* Breadcrumb Section */}
        <section className="relative bg-gray-50 py-8">
          <div className="absolute inset-0 bg-black opacity-50"></div>
          <div className="container mx-auto px-4 relative z-10">
            <div className="flex flex-col items-center text-center">
              {/* Breadcrumb */}
              <div className="flex items-center justify-center space-x-2 text-sm mb-4">
                <span className="text-gray-600">Home</span>
                <span className="text-gray-400">
                  <i className="fas fa-chevron-right text-xs"></i>
                </span>
                <span className="text-red-600 font-semibold">Privacy Policy</span>
              </div>
              
              {/* Main Title */}
              <h1 className="text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
            </div>
          </div>
        </section>

        {/* Privacy Policy Content */}
        <section className="py-12">
          <div className="container mx-auto px-4 max-w-4xl">
            <div className="prose prose-lg max-w-none">
              <PrivacyPolicyContent />
            </div>
          </div>
        </section>
      </main>

      <StickyContact />
    </>
  );
}

// Privacy Policy Content Component
function PrivacyPolicyContent() {
  return (
    <>
      <p>This Proforce1 Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      
      <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

      <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>
      
      <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      
      <ul className="list-disc pl-6 space-y-2 mt-4">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to PROFORCE1 PROTECHTION SERVICES.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: California, United States</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to PROFORCE1 PROTECHTION SERVICES, accessible from <a href="https://proforc1.com/" className="text-red-600 hover:underline">https://proforc1.com/</a></li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      {/* Continue with all the privacy policy sections from the original HTML */}
      {/* ... rest of the privacy policy content ... */}

      <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      
      <ul className="list-disc pl-6 space-y-2 mt-4">
        <li>By email: INFO@PROFORCE1PROTECTION.COM</li>
        <li>By phone number: (800) 779-7691</li>
      </ul>
    </>
  );
}